export class Plugin {}
export class PluginSettingTab {}
export class ItemView {}
export class Modal {}
export class Notice {}
export class TFile {}
export class TFolder {}
export class Setting {}
export class SecretComponent {}
export class MarkdownRenderer {}
export class Menu {}
export class MarkdownView {}
export class App {}
export class Editor {}
export class WorkspaceLeaf {}
